### ISSUE TITLE
SuiteCRM LTS version

### ISSUE THREAD

**Issue by ghost** [bitnami/bitnami-docker-suitecrm#103]
**Description**

I can't find any docker tags for LTS versions. Do they exist?
Also I can't find the currently designated LTS version number 7.10.22 in the tags. I see no tag starting with "7.10" above "7.10.11".

Am I missing something?

**Comment by jotamartos** [comment]
Hi @EZS-JD,

We released SuiteCRM 7.10.11 and you can find all the tags in DockerHub

https://hub.docker.com/r/bitnami/suitecrm/tags?page=1&name=7.10

You can pull the last release we made of this version using this command 

```
docker pull bitnami/suitecrm:7.11.10
```

**Comment by jotamartos** [comment]
Hi @EZS-JD,

7.11.10 was the latest version of SuiteCRM that was released in its Github repository 

https://github.com/salesagility/SuiteCRM/releases

You can also find that information in its official page. 

https://suitecrm.com/download/

Where did you find the 7.10.22 version?

**Comment by jotamartos** [comment]
Hi @EZS-JD,

We only provide the latest version of SuiteCRM in our container solution. We stopped to publish the version 7.10 when the version 7.11.x was released and that's why you can't find the latest LTS version. 

Sorry for the inconvenience.

**Comment by EZS-JD** [comment]
That's a bummer!
1. Please consider supporting LTS versions, even if version number is "outdated"
2. I would highly welcome a rolling LTS tag, so I don't have to manually pick and choose version numbers.

As I understand the LTS versions are the most stable and secure versions of SuiteCRM.

**Comment by sameersbn** [comment]
@EZS-JD thanks for bringing this to our attention. We will evaluate this request internally and get back with you.

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-suitecrm#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
