### ISSUE TITLE
Feature Request - Include ElasticSearch in docker compose

### ISSUE THREAD

**Issue by dpieski** [bitnami/bitnami-docker-suitecrm#105]
Feature Request is evident from the title. 
Can you include the elasticsearch image in the docker-compose file?

SuiteCRM docs for elasticsearch integration are available here: https://docs.suitecrm.com/admin/administration-panel/search/elasticsearch/

**Comment by carrodher** [comment]
Hi, I am sorry but according to the doc:
> This enhancement is only available in SuiteCRM from version 7.11 onwards.

The provided `docker-compose.yaml` should work with different versions, just replacing the image tag.
In the same way, we provide a basic functional `docker-compose.yaml` but this file doesn't cover all the use cases that an application can support, users can clone the repo or download the file to modify it to meet their specific needs.

**Comment by dpieski** [comment]
oh my bad. I thought you were concerned with the latest release of SuiteCRM in the yaml file. I didn't realize you intended people to use outdated versions.

I read through the Docs, are there other third-party apps that integrate into the base functioning of SuiteCRM other than MariaDB and ElasticSearch?

**Comment by sameersbn** [comment]
@dpieski I think you have misunderstood. We want the **default** `docker-compose.yaml` file to be compatible with older versions of the app so that users can update the docker image tag and switch to a different version if they so choose to. 

By adding elasticsearch to the default `docker-compose.yaml` we would be forcing users to deploy elasticsearch even if they don't see a need for it. IMO advanced users such as yourself should not have an issue updating the yaml file to launch elasticsearch
