### ISSUE TITLE
Attachments in email are not being sent

### ISSUE THREAD

**Issue by agile2go** [bitnami/bitnami-docker-suitecrm#111]
Thank you for a great package. I am using it and am very happy!

**Description**

I did come over a problem with the email service, specifically when attaching an attachment to the email, that causes the email to be sent without the attachment - no errors/warnings that I can see. Attachment is stored in SuiteCRM, just not sent to receiver.

**Steps to reproduce the issue:**

1.  (assuming container is setup and email configuration is setup and working)
2. Activities -> Email -> Compose
3. Specify From, To, Subject and Body and include an attachment file.

**Describe the results you received:**

You will see that the email will not include an attachment.

**Describe the results you expected:**

I would expect the email to be sent with the attachment as requested. The attachment is stored within SuiteCRM, however it is not sent in the outgoing email. Fixing the issue with the fix below does cause the email to include the attachment as expected.

**Additional information you deem important (e.g. issue happens only occasionally):**

I managed to fix this issue based on the discussion groups by adding a symbolic link with the following command:

 ln -s /bitnami/suitecrm/94288-upload /bitnami/suitecrm/upload

(I assume the integer - 94288 could be different on different installations)

**Version**

7.11.13-debian-10-r41

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Running Docker on Windows 10 Professional.

**Comment by andresbono** [comment]
Hi @agile2go, Thanks for opening this issue and providing a workaround for it.

We will try to add a fix in the image, but in the meantime, we will keep this issue open so others can benefit from your solution.

Thanks again!

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-suitecrm#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
