### ISSUE TITLE
Cron in Docker-Swarm

### ISSUE THREAD

**Issue by bd8392** [bitnami/bitnami-docker-suitecrm#115]
Hi =) There is a problem with the cronjobs...I can't configure it in docker-swarm, as the containernames differ from time to time. Also Suitecrm doesn't support webcron...Is there a possibility to insert a variable to the container, that states how often the cron is executed? This would solve all problems with cronjobs inside =)

**Comment by dani8art** [comment]
Hi @bd8392 , thank you for opening the issue.

Why docker-swarm changes the names? I guess because it is rescheduling the container or scaling it out/in, right?

Why do you think cronjobs depend on container's names? it shouldn't.

If the cronjobs depend on the container's names, why giving them the possibility of configure its triggering time would resolve the problem?
