### ISSUE TITLE
Consume SuiteCRM Api with docker image?

### ISSUE THREAD

**Issue by SAGOlab** [bitnami/bitnami-docker-suitecrm#116]
Hi there,

I have pull the docker.io/bitnami/suitecrm:7-debian-10 docker image from dockerhub.

Now I need to consume suitecrm api and per documentation ([suitecrm docs](https://docs.suitecrm.com/developer/api/developer-setup-guide/json-api/)) you need to set both private and public key.

I need to extend the image with a custom entrypoint that create the key in the container or is a step that I could skip with docker?

thanks a lot.

**Comment by marcosbc** [comment]
Hi @SAGOlab, currently the easiest way for you to apply these changes would be to extend the Docker image to create the keys (at build time).

If that is not an option, and since the SuiteCRM container persists all SuiteCRM files across restarts, you could always add the files on the fly (i.e. via `docker cp`).

(NOTE: Due to SuiteCRM container persisting all SuiteCRM files across restarts, upgrades are impossible and unfortunately you won't be able to mount the public/private keys directly via `docker-compose`.)

**Comment by SAGOlab** [comment]
thanks a lot for the support,

I think the first option is the useful one for me.

Have a nice day.

**Comment by marcosbc** [comment]
Thanks for the update! Closing this issue then.

**Comment by officialasit** [comment]
Hi @SAGOlab . Im also looking for the same. Could you post the Dockerfile for that build. It would be very useful.
Thanks in advance.
