### ISSUE TITLE
Unable to load dynamic library 'imap.so'

### ISSUE THREAD

**Issue by sutidor** [bitnami/bitnami-docker-suitecrm#119]
**Description**

imap.so extension is missing in the installation:

PHP Warning:  PHP Startup: Unable to load dynamic library 'imap.so' (tried: /opt/bitnami/php/lib/php/extensions/imap.so (/opt/bitnami/php/lib/php/extensions/imap.so: cannot open shared object file: No such file or directory), /opt/bitnami/php/lib/php/extensions/imap.so.so (/opt/bitnami/php/lib/php/extensions/imap.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

**Steps to reproduce the issue:**

install suiteCRM container as described

**Describe the results you received:**

spins up normally, but imap.so php extension is missing and can't be found anywhere on the container with find / -name imap.so

**Describe the results you expected:**

imap.so installed along with php

**Version**
docker version 19.03.13
latest suitecrm Version 7.11.15

**Comment by javsalgar** [comment]
Hi,

Thanks for letting us know. I will open a task for investigation. As soon as there are more news, we will update this ticket.

**Comment by l4b4r4b4b4** [comment]
Same error here. Hints for a fix are highly appreciated ;)

**Comment by marcosbc** [comment]
Hi all, we are working on some major changes affecting the SuiteCRM container, and it looks like we are expecting to include this fix. It should be out by the end of this week.

Unfortunately it looks like there is no workaround, as compiling imap for PHP requires re-compiling the entire PHP source: https://www.php.net/manual/en/imap.installation.php

**Comment by l4b4r4b4b4** [comment]
Thanks a lot for the feedback 🙏
Ill be waiting for the end of the week then, hoping the fix will be included. 🤠

**Comment by l4b4r4b4b4** [comment]
Thanks a lot for the feedback 🙏
Ill be waiting for the end of the week then, hoping the fix will be included. 🤠

**Comment by l4b4r4b4b4** [comment]
Could you give an update? 

Thanks a lot in advance

**Comment by FraPazGal** [comment]
Hi @l4b4r4b4b4,

The refactoring of the SuiteCRM container is still ongoing and we are actively working on it. I will update this issue as soon as there are any more news, thank you for your patience!

**Comment by l4b4r4b4b4** [comment]
thx a lot for the clarification!

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-suitecrm#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
