### ISSUE TITLE
make the API work [problem + solution]

### ISSUE THREAD

**Issue by sutidor** [bitnami/bitnami-docker-suitecrm#124]
**Description**

The rewrite for the api does not work. 

{{suitecrm.url}}/Api/access_token, if all is working correctly, in the browser should show  `Method not allowed Must be one of: POST` but shows `404 not found`. The issue is not due to reverse proxy as the suitecrm container shows 404 in the logs, too.

https://docs.bitnami.com/general/apps/suitecrm/administration/use-htaccess/#understand-htaccess-files
According to the docs, the value should be`AllowOverride All` but in the actual image it is `AllowOverride None`.

**Solution**
Change `/opt/bitnami/apache2/conf/vhosts/suitecrm-https-vhost.conf` (if you are using https) `suitecrm-vhost.conf` (if you are using plain http)
`AllowOverride All`

Because the docs are right and the image is different, I suppose it is a bug, not a security feature.

Edit: Found the files in question
https://github.com/bitnami/bitnami-docker-suitecrm/tree/master/7/debian-10/rootfs/opt/bitnami/scripts/apache/bitnami-templates
The override is parameterized

**Comment by FraPazGal** [comment]
Hi @sutidor,

Thank you for using our container! This is the expected behaviour as by default the rewrite module is installed and configured but not enabled. As per [SuiteCRM documentation](https://docs.suitecrm.com/developer/api/developer-setup-guide/json-api/#_before_you_start_calling_endpoints), changing `AllowOverride` to `All` is part of the API configuration. As you would also need to create the encryption keys, all of this steps are thought to be made by customising our image. You can find more info of this on our [README](https://github.com/bitnami/bitnami-docker-suitecrm#customize-this-image).

**Comment by sutidor** [comment]
Thanks for coming back, I issued a PR to update the readme.
