### ISSUE TITLE
SuiteCRM en ECS y RDS AWS

### ISSUE THREAD

**Issue by jhonmartinezb** [bitnami/bitnami-docker-suitecrm#133]
**Description**

Good night,
I would like to know for the SuiteCRM product on AWS, for a recurring access of approximately 500 users, which capacities recommend should be approved to deploy the service on ECS (Elastic Container Service) for the application topic (How many Vcpus and how much RAM for each container or containers) and what capabilities for the Database if I deploy it in MySQL RDS.
Please add some documentation for the deployment of SuiteCRM in ECS with BD in AWS RDS.
Thanks!

**Comment by carrodher** [comment]
Hi,

About the connection of the Bitnami SuiteCRM container image with an external database, there is some information in the README describing what are the required environment variables that are needed to set, see https://github.com/bitnami/bitnami-docker-suitecrm#use-an-existing-database and/or https://github.com/bitnami/bitnami-docker-suitecrm#create-a-database-for-suitecrm-using-mysql-client

Regarding the machine requirements I would recommend you to ask in a SuiteCRM specialized forum since here, from Bitnami, we package the Open Source applications but we are not experts in all the applications from the catalog. That's why I think in the SuiteCRM community you will find more precise information on this topic, such as https://community.suitecrm.com/t/minimum-server-droplet-requirements/58110

**Comment by jhonmartinezb** [comment]
Muchas gracias por la respuesta!
