### ISSUE TITLE
Stable Branch Release

### ISSUE THREAD

**Issue by sergtech** [bitnami/bitnami-docker-suitecrm#69]
This is more of a feature request.
Is it possible to have an alternate branch that follows the LTS version of SuiteCRM? 
The incremental builds are often buggy, while the LTS versions are generally much more stable (but currently have lower version numbering).
Cheers.

**Comment by juan131** [comment]
Hi @sergtech 

At this moment we don't plan to maintain more than one branch for SuiteCRM Docker Image. However, it might be interesting to move the current version to the latest LTS version (7.8.8) and continue updating only with LTS versions instead of using the latest build. What do you think @tompizmor ?

**Comment by jloramas** [comment]
@sergtech Thanks for your suggestion. We will take it into account the next time we review our release policy, which currently is to release the latest version.

I will proceed to close this case.

**Comment by lid** [comment]
+1 Would love to have a more stable version available (e.g. 7.8.18 LTS); the bleeding edge is a little rough.

**Comment by juan131** [comment]
Thanks for your suggestion. I'd share it with the team.

cc/ @jloramas @tompizmor

**Comment by jloramas** [comment]
Thx @juan and @lid. I will bring up the review of our containers release policy to the team.
