### ISSUE TITLE
Suitecrm container dies when initializing

### ISSUE THREAD

**Issue by colintanlk** [bitnami/bitnami-docker-suitecrm#73]
**Description**

Trying to install suitecrm as per instructions. Used both methods, compose as well as manual. Accessed using 127.0.0.1, website comes up and starts initializing for a long time. Dies when the container exits

**Steps to reproduce the issue:**

1. Used compose to bring up containers, they have random names
2. Firefox to access 127.0.0.1
3  Dies after 10 minutes while trying to initialize
4. Check docker ps and the container is gone

**Describe the results you received:**
Dies

**Describe the results you expected:**

Initializes

**Additional information you deem important (e.g. issue happens only occasionally):**

inux colintan-945GCM-S2L 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:11:19 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:09:53 2017
  OS/Arch:	linux/amd64
  Experimental:	false

```


Containers: 7
 Running: 1
 Paused: 0
 Stopped: 6
Images: 31
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.10.0-42-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 2.928GiB
Name: colintan-945GCM-S2L
ID: MEOG:SBOU:LZIO:DAFC:2JVJ:HC7H:46PU:KAUH:WHRL:PQRX:TYVG:3ODO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.8.0, build unknown
docker-py version: 1.9.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016

```

echo $BITNAMI_IMAGE_VERSION
7.9.8-r0

**Comment by juan131** [comment]
Hi @colintanlk 

I was unable to reproduce the issue as you can check in the docker-compose' output below, SuiteCRM was initialised:

```
...
suitecrm_1  | suitecr INFO  Configuring Database...
suitecrm_1  | mysql-c INFO  Trying to connect to MySQL server
suitecrm_1  | mysql-c INFO  Found MySQL server listening at mariadb:3306
suitecrm_1  | mysql-c INFO  MySQL server listening and working at mariadb:3306
suitecrm_1  | suitecr INFO  Configuring silent installation
suitecrm_1  | suitecr INFO  Installing suitecrm. It could take some minutes...
suitecrm_1  | suitecr INFO  Setting extra configuration...
suitecrm_1  | suitecr INFO  Cleaning up folders..
suitecrm_1  | suitecr INFO  Configuring Cron Jobs...
suitecrm_1  | suitecr INFO  Configuring permissions...
suitecrm_1  | suitecr INFO
suitecrm_1  | suitecr INFO  ########################################################################
suitecrm_1  | suitecr INFO   Installation parameters for suitecrm:
suitecrm_1  | suitecr INFO     Username: user
suitecrm_1  | suitecr INFO     Last name: Name
suitecrm_1  | suitecr INFO     Password: **********
suitecrm_1  | suitecr INFO     Email: user@example.com
suitecrm_1  | suitecr INFO   (Passwords are not shown for security reasons)
suitecrm_1  | suitecr INFO  ########################################################################
suitecrm_1  | suitecr INFO
suitecrm_1  | nami    INFO  suitecrm successfully initialized
suitecrm_1  | INFO  ==> Starting suitecrm...
suitecrm_1  | 127.0.0.1 - - [08/Jan/2018:11:24:39 +0000] "GET /themes/SuiteP/css/bootstrap.min.css HTTP/1.1" 200 147328
suitecrm_1  | 127.0.0.1 - - [08/Jan/2018:11:24:39 +0000] "GET /themes/SuiteP/css/fonts.css HTTP/1.1" 200 7094
suitecrm_1  | 127.0.0.1 - - [08/Jan/2018:11:24:39 +0000] "GET /themes/SuiteP/css/grid.css HTTP/1.1" 200 1122
suitecrm_1  | 127.0.0.1 - - [08/Jan/2018:11:24:39 +0000] "GET /themes/SuiteP/css/footable.core.css HTTP/1.1" 200 9903
```

**Comment by juan131** [comment]
Could you please take a look to the issue https://github.com/bitnami/bitnami-docker-suitecrm/issues/24? I think it could be the same problem

**Comment by ndarilek** [comment]
Similar setup, but it seems distinct from #24 because I don't get to the point where the site comes up.

I'm using an external MySQL database hosted on Microsoft Azure. The container is on a clean Docker host, with the latest image pulled as of 20 minutes ago. Here's my docker-compose.yml:

```
version: "3"

volumes:

  caddy:

  data:

services:

  crm:
    image: bitnami/suitecrm
    environment:
      SUITECRM_DATABASE_NAME: suitecrm
      suitecrm_username: admin
      NAMI_DEBUG: "--log-level trace"
      BASH_DEBUG: "1"
    env_file: .env
    volumes:
      - data:/bitnami
      - ./my.cnf:/opt/bitnami/mysql/conf/my.cnf
    ports:
      - "80:80"
      - "443:443"

```

my.cnf, needed to enable SSL from the MySQL client:

```
[mysql]
ssl=1
```

Everything goes well in the logs, until:

```
[36mcrm_1  |[0m suitecr INFO  Installing suitecrm. It could take some minutes...
[36mcrm_1  |[0m Error executing 'postInstallation': Error trying to install the application
[36mcrm_1  |[0m nami    TRACE Error: Error executing 'postInstallation': Error trying to install the application
[36mcrm_1  |[0m     at Object.$app.helpers.passWizard (/root/.nami/components/com.bitnami.suitecrm/helpers.js:35:11)
[36mcrm_1  |[0m     at Component.$app.postInstallation (/root/.nami/components/com.bitnami.suitecrm/main.js:100:20)
[36mcrm_1  |[0m     at Component.runStep (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:159:12)
[36mcrm_1  |[0m     at _.each.step (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:32)
[36mcrm_1  |[0m     at ot (/opt/bitnami/nami/node_modules/lodash/index.js:12:507)
[36mcrm_1  |[0m     at Function.<anonymous> (/opt/bitnami/nami/node_modules/lodash/index.js:33:421)
[36mcrm_1  |[0m     at Component.install (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:7)
[36mcrm_1  |[0m     at Manager.initializePackage (/opt/bitnami/nami/node_modules/nami-core/lib/manager.js:284:11)
[36mcrm_1  |[0m     at Command.cmdOpts.callback (/opt/bitnami/nami/cli/nami-app.js:331:24)
[36mcrm_1  |[0m     at NamiParser.parseCommands (/opt/bitnami/nami/node_modules/cmd-parser/index.js:518:30)
[36mloconomics_crm_1 exited with code 1
```

I do have this running locally with a self-contained database, so I know it works. I can't get it running in production with an external Azure database, though. I can connect to the database via the command line client from the container, so that much definitely works.

Thanks, happy to provide any additional details.

**Comment by juan131** [comment]
Hi @ndarilek 

In order to use a external database, you also need to indicate the env. variables **MARIADB_HOST**, **MARIADB_PORT_NUMBER**, ** SUITECRM_DATABASE_USER** and ** SUITECRM_DATABASE_PASSWORD** as explained on the README.md:

https://github.com/bitnami/bitnami-docker-suitecrm#environment-variables

Could you please try using those env. variables?

**Comment by ndarilek** [comment]
Already done, that's handled by:

```
    env_file: .env
```

from the pasted docker-compose.yml, and all of those variables are
correctly defined in _.env_. This is confirmed by the initial mysql
client connections, which succeed.

**Comment by juan131** [comment]
Hi @ndarilek 

SuiteCRM is initialised following some logic which is included in the SuiteCRM [Nami](https://github.com/bitnami/nami) module. That passes the installation Wizard of SuiteCRM. 

It seems it's failing because of a problem during the wizard installation. It's very likely the problem is that  it's unable to connect to MySQL since it's not configuring the file `config_si.php` taking that into account the connection is using SSL before running the wizard.

@tompizmor what do you think?

**Comment by ndarilek** [comment]
Got it, thanks. You gave me a configuration in the forum. Is there any
way I might inject that configuration so the problematic step gets
skipped? If so, what would a full configuration file look like? I
imagine there's more than just the database config.

**Comment by ndarilek** [comment]
It occurs to me that I may be able to temporarily disable SSL on the
Azure database, launch the container, edit the config to enable SSL as
per your instructions on the forum, then relaunch the container with the
new configuration.

Startup time seems a bit slow. Under what circumstances is that rerun?
If I disable then re-enable SSL, I'll have to modify the docker-compose
configuration, which will recreate the container but shouldn't recreate
the volume. If the container finds its configuration files in the
persistent volume, will it not rerun the startup/installation procedure
that is erroring out?

And is there any way for me to get a log of what commands are being run
and, by extension, failing? The installation process hits a point where
it pauses for several minutes. Might be nice to get some feedback from
that process so I can determine that the crash is due to database
configuration issues.

Thanks!

**Comment by ndarilek** [comment]
Having disabled SSL on the database, I'm now hitting #24. So I guess this was indeed an SSL issue. Hoping the container doesn't attempt to reconfigure itself on every launch.
