### ISSUE TITLE
plugins and symlinks

### ISSUE THREAD

**Issue by kalvdans** [bitnami/bitnami-docker-suitecrm#80]
**Description**

Installation of Fanatical Labs zendesk-sugarcrm plugin[1] does not work out of the box in bitnami's suitecrm installation.

[1] https://www.sugaroutfitters.com/addons/zendesk-sugarcrm

**Steps to reproduce the issue:**

1. Fire up bitnami-docker-suitecrm 9fce31e4, using `docker-compose up`
2. Complete the SuiteCRM installation procedure using a web browser.
3. Register for a free trial at sugaroutfitters, get license code and download FanaticalZendesk-2.2.2-for-SuiteCRM.zip
4. Install that plugin in your bitnami SuiteCRM instance.

**Describe the results you received:**

The license code you enter in installation step 3 is not saved for later.

**Describe the results you expected:**

The license code you enter in installation step 3 should be saved, and visible when you reload the installation step 3 page later. Instead, it shows `false` as the license code.

**Version**

- Output of `docker version`:

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.8.3
 Git commit:   092cba3
 Built:        Thu Oct 12 22:34:44 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   092cba3
 Built:        Thu Oct 12 22:34:44 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

- Output of `docker info`:

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 11
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 71
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.13.0-32-generic
Operating System: Ubuntu 17.10
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 6.759 GiB
Name: yngvi
ID: KJKN:TGOD:RQRV:IYIL:UBBP:FL56:2HLQ:QTPI:X27D:IHUS:26BM:4E26
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.8.0, build unknown
docker-py version: 1.9.0
CPython version: 2.7.14
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
```

**Comment by kalvdans** [comment]
The license code is saved in `/bitnami/suitecrm/config_override.php` but that file needs to be in `/opt/bitnami/suitecrm/` directory to be picked up. Bug #50 claims to have fixed this particular error, though.

After working around that bug, next error was requests to `/custom/service/FanaticalZendesk/rest.php` returning status 500. Logs from apache shows
```
[Thu Mar 22 14:48:27.691670 2018] [:error] [pid 72] [client 192.168.1.15:55570] PHP Fatal error:  require_once(): Failed opening required 'service/v4_1/SugarWebServiceImplv4_1.php' (include_path='.:/opt/bitnami/php/lib/php') in /bitnami/suitecrm/custom/service/FanaticalZendesk/SugarWebServiceImplFanaticalZendesk.php on line 6, referer: https://orexplore.zendesk.com/agent/users/361185438893/assigned_tickets
```
That problem could be fixed by a symlink pointing back to SuiteCRM root from the SuiteCRM volume.

`ln -s /opt/bitnami/suitecrm/service /bitnami/suitecrm/service`

**Comment by chadhutchins** [comment]
Thanks @kalvdans for posting this. I am with Fanatical Labs who owns the SuiteCRM/Zendesk integration being referred to. 

The steps used above had to be applied to get our integration working on SuiteCRM/Bitnami. 

I'm curious in general what the steps are for someone to install a module in SuiteCRM when it's running on Bitnami? It seems like this issue would happen for any module that tries to get installed.

**Comment by javsalgar** [comment]
Hi,

The issue has to do with persistence. In order to maintain persistence, some folder are symlinked to `/bitnami/` (everything in this folder will be persisted). It is highly likely that the plugin makes use of relative paths (such as `..`), therefore it will fail to properly locate certain files or directories. In principle, we do not want to persist the whole installation as it could be problematic with upgrades. However, we will need to see how common is the use of relative paths in plugins. I will forward this information to the rest of the team.

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-suitecrm#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
