### ISSUE TITLE
Tag latest does not contain latest suitecrm version

### ISSUE THREAD

**Issue by bkraul** [bitnami/bitnami-docker-suitecrm#88]
**Description**

The ```latest``` tag does not contain the latest suitecrm version (around 7.10.x), it instead contains version 6.5.25 (Build 344).

**Steps to reproduce the issue:**

1. Pull ```bitnami/suitecrm:latest```
2. Run
3. To to Project's About screen

**Describe the results you received:**

About gives a much older version 6.5.25 (Build 344).

**Describe the results you expected:**

Expected to see closer to version 7.10

**Version**

- Output of `docker version`:

```
18.06.0-ce
```

- Output of `docker info`:

```
Containers: 14
 Running: 13
 Paused: 0
 Stopped: 1
Images: 17
Server Version: 18.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-29-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.853GiB
Name: docker
ID: X777:P7YR:LILB:TJV4:YWAV:MBHI:MPIA:GSYV:MUJ2:5YLD:PJOU:K2MP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.22.0, build f46880f
```

**Comment by bkraul** [comment]
From my docker pull results I would expect that the ```7.10.7``` tag is also pulling an older version because its hash is the same as latest.

**Comment by bkraul** [comment]
Any info on this? The image keeps getting updated but the version of suitecrm is the same. Is there anything the user needs to do to keep this updated aside from pulling the newest image?

**Comment by marcosbc** [comment]
Hi @bkraul, actually SuiteCRM's `latest` tag has the proper version, currently 7.10.7.

The version shown in the "About" screen refers to the SugarCRM version that SuiteCRM is based on. Note that SuiteCRM is a SugarCRM fork.

If you have any doubt, you can verify your SuiteCRM version in the following file inside the container:

    /opt/bitnami/suitecrm/suitecrm_version.php

You should see a line like the following:

    $suitecrm_version      = '7.10.7';

**Comment by bkraul** [comment]
I see what you are saying. However, there still seems to be something strange. I took a zipball from suitecrm's latest release and installed on an old-fashioned vps. The following is the About box. I do notice the SugarCRM version being the same as the bitnami version:

![image](https://user-images.githubusercontent.com/14616851/43715995-0b8a65d4-9948-11e8-9dd0-d3f8a2863419.png)

However, the bitnami release shows no version on the About screen. This is what originally led me to believe I had an older version.

![image](https://user-images.githubusercontent.com/14616851/43716025-28047916-9948-11e8-8118-0a01a939eeb3.png)

Is there something that is turned off in the options by default by bitnami to hide the version?

**Comment by lid** [comment]
@bkraul see #79 and #78. The underlying include_path issue needs to be resolved, but there is a workaround.

**Comment by bkraul** [comment]
I was able to workaround using #79, at least until the next pul...I wonder though...why are the issues being closed when there is no actual official resolution to the issues?

**Comment by marcosbc** [comment]
Hi, you're totally right, the version should appear there. That is a bug and it is happening because `/opt/bitnami/suitecrm` is not in PHP's include path.

For now, you can fix this specific issue on your own by executing the command below:

    sed -i "s:'suitecrm_version.php':'/opt/bitnami/suitecrm/suitecrm_version.php':" /bitnami/suitecrm/modules/Home/About.php

However, we need to fix this in the image since it's affecting other parts of the application as well. The fix should happen in the next couple of weeks.

**Comment by marcosbc** [comment]
Hi @bkraul and @lid, we have an update on the progress of fixing this issue permanently.

Due to it affecting both plugins and native SuiteCRM components, we will proceed with persisting the **entire** `htdocs` directory.

This means the only way to upgrade is to follow the process manually, via the app's upgrade wizard, but we will update the README. Upgrades done by pulling the new container will obviously not work for this reason.

We are already working on releasing this, and it should be available soon.

**Comment by bkraul** [comment]
So I must ask, what will then be the point of running your container, versus setting up a bare web/php environment and pulling the SuiteCRM master to run it? I am not sure I follow the logic for the decision, I suppose other than the complexity of the installation.

**Comment by marcosbc** [comment]
@bkraul We understand you concern. The container allows you to have a running copy of SuiteCRM in a couple of minutes, without having to worry about configuration.

However, there are certain applications that are not designed to be run natively with containers, or that make it really difficult if you want to be able to support things such as extensions.

That is not the case of SuiteCRM, as it does not have a clear boundary between core code (which may change after each release), and configuration and customizations such as modules, themes or other changes (which rarely changes, and if it is the case, the application will rarely be broken).

Some applications such as WordPress work pretty well in containers, as you only need to preserve "wp-content" and "wp-config.php" (and possible ".htaccess"), the rest is all core code which you should never have to worry about.

Therefore, in the case of SuiteCRM, users would lose the ability to upgrade automatically when a new container version is available. However, due to the reasons we pointed out above, we believe it makes the most sense for users to take care of upgrading the application on their side.
Fortunately the application provides an upgrade wizard to make things easier (we will update our README with the proper steps).

Please let us know if you have any questions.

**Comment by marcosbc** [comment]
Hi @bkraul, we released the following SuiteCRM container releases, which implements the changes we mentioned in previous comments:

- **7.10.10-debian-9-r19**
- **7.10.10-ol-7-r26**

We also updated the [README](https://github.com/bitnami/bitnami-docker-suitecrm/#upgrade-this-application) to reflect these changes.

I'm going to describe below how to migrate previous releases of the container to the newest release. Please let us know if you find any issues.

____

In order to **migrate** from previous releases (7.10.10-debian-9-r19, 7.10.10-ol-7-r23 or prior releases) please follow these steps:

- Create backups in case something goes wrong:

  * SuiteCRM container: Backup all persist data located at `/bitnami/suitecrm`.
  * MariaDB database: [Create a backup](https://docs.bitnami.com/bch/apps/redmine/administration/backup-restore-mysql-mariadb/) of SuiteCRM's database.

- Start a new SuiteCRM container. You might need to specify a different port configuration in order to have both the current (with the new changes) and previous container release (without them) running. Ensure docker-compose is creating a different container, with different volumes.

- Migrate SuiteCRM `htdocs` directory:

  * Inside the original SuiteCRM container, compress the entire SuiteCRM folder, following any symlink and creating the ".initialized" (so it has the same format as newer releases of the container):

        cd /opt/bitnami/suitecrm
        tar czfh /tmp/suitecrm-htdocs.tar.gz .

  * Copy the compressed tarball to the outside of the container (supposing below its id is 0123456789ab):

        docker cp 0123456789ab:/tmp/suitecrm-htdocs.tar.gz .

  * Copy that tarball to the new SuiteCRM container, which includes the new changes (supposing below its id is abcdef012345): 

        docker cp suitecrm-htdocs.tar.gz abcdef012345:/tmp

  * Inside the new SuiteCRM container, with the new changes, replace `/bitnami/suitecrm` with the contents of the tarball:

        rm -rf /bitnami/suitecrm/*
        tar xzf /tmp/suitecrm-htdocs.tar.gz -C /bitnami/suitecrm

- Restore the MariaDB database:

  * [Create a backup](https://docs.bitnami.com/bch/apps/redmine/administration/backup-restore-mysql-mariadb/) of the old MariaDB database container (supposing below its id is 54321abcdef):

        docker exec 012345abcdef mysqldump -u root bitnami_suitecrm > suitecrm-db.sql

  * Copy the backup to the new MariaDB container (supposing its id is fedcba012345):

        docker cp suitecrm-db.sql fedcba012345:/tmp

* [Restore the backup](https://docs.bitnami.com/bch/apps/redmine/administration/backup-restore-mysql-mariadb/), inside the new MariaDB database container:

        mysql -u root bitnami_suitecrm < /tmp/suitecrm-db.sql

* Stop the old SuiteCRM and MariaDB container (using the old `docker-compose.yml` file).
* Restart the new SuiteCRM and MariaDB container (using the new `docker-compose.yml` file).

**Comment by bkraul** [comment]
Marcos, thank you for this. I have, however, moved to self-maintained SuiteCRM. Hopefully your changes will help with the rest of the installations. I did try the steps above, but because I have several module customizations, it became quite complicated, which is why I opted for a more direct approach. I am closing this issue, as it is no longer an issue for me, and your changes address it in the long term.
